"""create medical tables

Revision ID: 31f9f0473e87
Revises: 
Create Date: 2026-05-09 05:39:05.172843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f9f0473e87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_code', sa.String(length=20), nullable=False, comment='병원 내부 환자 번호 (예: P123456)'),
    sa.Column('name_encrypted', sa.Text(), nullable=True, comment='암호화된 환자 이름'),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=True),
    sa.Column('primary_diagnosis_code', sa.String(length=10), nullable=True, comment='주 진단 ICD 코드 (예: H36.0)'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_patient_code'), 'patients', ['patient_code'], unique=True)
    op.create_table('eye_exams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('exam_type', sa.Enum('FUNDUS', 'OCT', 'VISUAL_FIELD', 'SLIT_LAMP', 'REFRACTION', 'IOP', name='examtypeenum'), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('icd_code', sa.String(length=10), nullable=True, comment='검사 관련 ICD-10 코드'),
    sa.Column('iop_left', sa.Float(), nullable=True, comment='좌안 안압 (mmHg)'),
    sa.Column('iop_right', sa.Float(), nullable=True, comment='우안 안압 (mmHg)'),
    sa.Column('visual_acuity_left', sa.String(length=10), nullable=True, comment='좌안 시력'),
    sa.Column('visual_acuity_right', sa.String(length=10), nullable=True, comment='우안 시력'),
    sa.Column('raw_findings', sa.Text(), nullable=True, comment='검사 원시 소견 (의사 입력)'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='LLM 생성 요약 소견'),
    sa.Column('report_status', sa.Enum('PENDING', 'GENERATING', 'COMPLETED', 'FAILED', name='reportstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eye_exams_patient_id'), 'eye_exams', ['patient_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('diagnosis_code', sa.String(length=10), nullable=False, comment='ICD-10 진단 코드'),
    sa.Column('diagnosis_name', sa.String(length=200), nullable=False, comment='진단명'),
    sa.Column('severity', sa.Enum('NORMAL', 'MILD', 'MODERATE', 'SEVERE', 'CRITICAL', name='diagnosisseverityenum'), nullable=False),
    sa.Column('report', sa.Text(), nullable=True, comment='LLM 생성 진단 보고서 (OntologyValidator 검증 완료)'),
    sa.Column('treatment_plan', sa.Text(), nullable=True, comment='치료 계획'),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('llm_iterations', sa.Integer(), nullable=False),
    sa.Column('llm_latency_ms', sa.Float(), nullable=True),
    sa.Column('ontology_passed', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='진단 신뢰도 (0.0~1.0)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['eye_exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_exam_id'), 'diagnoses', ['exam_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnoses_exam_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_eye_exams_patient_id'), table_name='eye_exams')
    op.drop_table('eye_exams')
    op.drop_index(op.f('ix_patients_patient_code'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
