"""add eye_images and knowledge tables with pgvector

Revision ID: c45bcf9c73f7
Revises: 31f9f0473e87
Create Date: 2026-05-09 08:02:09.256177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'c45bcf9c73f7'
down_revision: Union[str, None] = '31f9f0473e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False, comment='문서 제목'),
    sa.Column('content', sa.Text(), nullable=False, comment='문서 전체 내용'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='카테고리: diagnosis_criteria|treatment|icd_codes|protocol'),
    sa.Column('icd_codes', sa.JSON(), nullable=True, comment="관련 ICD-10 코드 목록 (예: ['H36.0', 'H40.1'])"),
    sa.Column('source', sa.String(length=200), nullable=True, comment='출처 (대한안과학회 가이드라인 등)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='긴 문서를 청크로 나눈 경우 순서'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_documents_category'), 'medical_documents', ['category'], unique=False)
    op.create_table('document_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('embedding', Vector(768), nullable=False, comment='벡터 임베딩 (768차원, nomic-embed-text-v1.5)'),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['medical_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_embeddings_document_id'), 'document_embeddings', ['document_id'], unique=True)
    op.create_table('eye_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=True, comment='연관 검사 기록 (선택적)'),
    sa.Column('image_type', sa.Enum('FUNDUS', 'OCT', 'SLIT_LAMP', 'VISUAL_FIELD', 'OTHER', name='imagetypeenum'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='컨테이너 내부 파일 경로 (/app/uploads/...)'),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='파일 크기 (bytes)'),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('analyzed', sa.Boolean(), nullable=False),
    sa.Column('analysis_result', sa.Text(), nullable=True, comment='VISION 모델 분석 결과 (JSON 문자열)'),
    sa.Column('analysis_icd_code', sa.String(length=10), nullable=True, comment='분석에서 추출한 ICD-10 코드'),
    sa.Column('analysis_severity', sa.String(length=20), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['eye_exams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eye_images_patient_id'), 'eye_images', ['patient_id'], unique=False)
    op.create_table('diagnosis_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('diagnosis_id', sa.String(length=36), nullable=False),
    sa.Column('diagnosis_code', sa.String(length=10), nullable=False, comment='ICD-10 코드 (필터링용)'),
    sa.Column('embedding', Vector(768), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True, comment='검색 시 유사도 점수 (임시 저장용)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_embeddings_diagnosis_code'), 'diagnosis_embeddings', ['diagnosis_code'], unique=False)
    op.create_index(op.f('ix_diagnosis_embeddings_diagnosis_id'), 'diagnosis_embeddings', ['diagnosis_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnosis_embeddings_diagnosis_id'), table_name='diagnosis_embeddings')
    op.drop_index(op.f('ix_diagnosis_embeddings_diagnosis_code'), table_name='diagnosis_embeddings')
    op.drop_table('diagnosis_embeddings')
    op.drop_index(op.f('ix_eye_images_patient_id'), table_name='eye_images')
    op.drop_table('eye_images')
    op.drop_index(op.f('ix_document_embeddings_document_id'), table_name='document_embeddings')
    op.drop_table('document_embeddings')
    op.drop_index(op.f('ix_medical_documents_category'), table_name='medical_documents')
    op.drop_table('medical_documents')
    # ### end Alembic commands ###
